//Edit offer
export const EDIT_OFFER = "EDIT_OFFER";

// OPEN JOBS COMPONENT

export const FILTER_JOBS = "FILTER_JOBS";
export const FETCH_JOB_BY_ID = "FETCH_JOB_BY_ID";
export const SET_ID_TO_APPLY = "SET_ID_TO_APPLY";
export const FETCH_JOB_INFO = "FETCH_JOB_INFO";
export const FILTER_JOBS_SUCCESS = "FILTER_JOBS_SUCCESS";
export const GET_JOB_DETAILS_BY_ID = "GET_JOB_DETAILS_BY_ID";
export const GET_JOB_APPLICANTS = "GET_JOB_APPLICANTS";
export const GET_JOB_DETAILS_BY_ID_SUCCESS = "GET_JOB_DETAILS_BY_ID_SUCCESS";
export const GET_WORK_START_SUCCESS = "GET_WORK_START_SUCCESS";

// FETCH AND OPEN JOBS OFFERS

export const GET_JOBS_OFFERS = "GET_JOBS_OFFERS";
export const GET_JOBS_OFFERS_SUCCESS = "GET_JOBS_OFFERS_SUCCESS";

// END

export const OPEN_AD_TO_SEE_AD_INFO = " OPEN_AD_TO_SEE_AD_INFO";
export const OPEN_AD_TO_SEE_AD_INFO_SUCCESS = " OPEN_AD_TO_SEE_AD_INFO_SUCCESS";
export const HIDE_SPINNER = " HIDE_SPINNER";
export const OPEN_APPLICANT_TO_SEE_APPLICATION =
  "OPEN_APPLICANT_TO_SEE_APPLICATION";
export const CHANGE_ADVERT_PAGE = "CHANGE_ADVERT_PAGE";

export const RESET_SEARCH_CRITERIA_FORM = "RESET_SEARCH_CRITERIA_FORM";

export const CHANGE_PAGINATION = "CHANGE_PAGINATION";

// CAMPAIGNS COMPONENT
export const CHOOSE_CAMPAIGN = "CHOOSE_CAMPAIGN";
export const GET_ALL_CAMPAIGNS = "GET_ALL_CAMPAIGNS";
export const GET_ALL_CAMPAIGNS_SUCCESS = "GET_ALL_CAMPAIGNS_SUCCESS";
export const SAVE_MARKETING_DETAILS = "SAVE_MARKETNG_DETAILS";
export const SAVE_MARKETING_DETAILS_SUCCESS = "SAVE_MARKETNG_DETAILS_SUCCESS";

// JOB CATEGORY COMPONENT
export const CHOOSE_JOB_CATEGORY = "CHOOSE_JOB_CATEGORY";
export const GET_ALL_JOB_CATEGORY = "GET_ALL_JOB_CATEGORY";
export const GET_ALL_JOB_CATEGORY_SUCCESS = "GET_ALL_JOB_CATEGORY_SUCCESS";
export const GET_ALL_JOB_CATEGORY_FROM_ESTONIA_SUCCESS =
  "GET_ALL_JOB_CATEGORY_FROM_ESTONIA_SUCCESS";

// REGISTER USER
export const SIGNUP_FORM_SUBMIT = "SIGNUP_FORM_SUBMIT";
export const SIGNUP_FORM_SUBMIT_SUCCESS = "SIGNUP_FORM_SUBMIT_SUCCESS";
export const SIGNUP_FORM_SUBMIT_USER_EXIST_ERROR =
  "SIGNUP_FORM_SUBMIT_USER_EXIST_ERROR";
export const SIGNUP_FORM_SUBMIT_FAILED = "SIGNUP_FORM_SUBMIT_FAILED";
export const CLOSE_SIGNUP_SNACKBAR = "CLOSE_SIGNUP_SNACKBAR";
export const SELECT_USER_TYPE = "SELECT_USER_TYPE";

// SIGNIN + SIGNOUT USER
export const SIGNIN_FORM_SUBMIT = "SIGNIN_FORM_SUBMIT";
export const SIGNIN_FORM_SUBMIT_SUCCESS = "SIGNIN_FORM_SUBMIT_SUCCESS";
export const SIGNIN_FORM_SUBMIT_FAILED = " SIGNIN_FORM_SUBMIT_FAILED";
export const CLOSE_SIGNIN_SNACKBAR = "CLOSE_SIGNIN_SNACKBAR";
export const CLIENT_SET = "CLIENT_SET";
export const CLIENT_UNSET = "CLIENT_UNSET";
export const LOGOUT = "LOGOUT";

// RESET PASSWORD
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUBMIT_SUCCESS = "RESET_PASSWORD_SUBMIT_SUCCESS";
export const RESET_PASSWORD_SUBMIT_FAILED = "RESET_PASSWORD_SUBMIT_FAILED";

// CHANGE PASSWORD
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUBMIT_SUCCESS = "CHANGE_PASSWORD_SUBMIT_SUCCESS";
export const CHANGE_PASSWORD_SUBMIT_FAILED = "CHANGE_PASSWORD_SUBMIT_FAILED";

// ADVERT FORM COMPONENT
export const POST_ADVERTISEMENT = "POST_ADVERTISEMENT";
export const SAVE_AND_PUBLISH_ADVERTISEMENT = "SAVE_AND_PUBLISH_ADVERTISEMENT";
export const SAVE_AND_PUBLISH_ADVERTISEMENT_TO_EE =
  "SAVE_AND_PUBLISH_ADVERTISEMENT_TO_EE";
export const UPDATE_AND_PUBLISH_ADVERTISEMENT =
  "UPDATE_AND_PUBLISH_ADVERTISEMENT";
export const SAVE_ADVERTISEMENT_AS_DRAFT = "SAVE_ADVERTISEMENT_AS_DRAFT";
export const SAVE_AND_PUBLISH_ADVERTISEMENT_SUCCESS =
  "SAVE_AND_PUBLISH_ADVERTISEMENT_SUCCESS";
export const SAVE_AND_PUBLISH_ADVERTISEMENT_TO_EE_SUCCESS =
  "SAVE_AND_PUBLISH_ADVERTISEMENT_TO_EE_SUCCESS";
export const UPDATE_AND_PUBLISH_ADVERTISEMENT_SUCCESS =
  "UPDATE_AND_PUBLISH_ADVERTISEMENT_SUCCESS";
export const SAVE_AND_PUBLISH_ADVERTISEMENT_FAILED =
  "SAVE_AND_PUBLISH_ADVERTISEMENT_FAILED";
export const RETRIEVE_IMAGE_INFO = "RETRIEVE_IMAGE_INFO";
export const RETRIEVE_LOGO_INFO = "RETRIEVE_LOGO_INFO";
export const RETRIEVE_DOCUMENT_INFO = "RETRIEVE_DOCUMENT_INFO";
export const RETRIEVE_PROFILE_PIC_INFO = "RETRIEVE_PROFILE_PIC_INFO";
export const CLEAR_IMAGES = "CLEAR_IMAGES";
export const CLEAR_COMPANY_LOGO = "CLEAR_COMPANY_LOGO";
export const CLEAR_JOBSEEKER_PROFILE_PIC = "CLEAR_JOBSEEKER_PROFILE_PIC";
export const WARN_TO_DELETE = "WARN_TO_DELETE";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_ADVERTISEMENT = "DELETE_ADVERTISEMENT";
export const DELETE_JOB_OFFER = "DELETE_JOB_OFFER";
export const UPDATE_ADVERTISEMENT = "UPDATE_ADVERTISEMENT";
export const POPULATE_VACANCY_FORM = "POPULATE_VACANCY_FORM";
export const EDIT_VACANCY_FORM = "EDIT_VACANCY_FORM";
export const POPULATE_VACANCY_FORM_SUCCESS = "POPULATE_VACANCY_FORM_SUCCESS";
export const CHANGE_CAMPAIGN = "CHANGE_CAMPAIGN";
export const SAVE_NEW_CAMPAIGN = "SAVE_NEW_CAMPAIGN";
export const SAVE_NEW_CAMPAIGN_SUCCESS = "SAVE_NEW_CAMPAIGN_SUCCESS";
export const CHANGE_ACTIVE_POST_TO_INACTIVE = "CHANGE_ACTIVE_POST_TO_INACTIVE";
export const GET_JOBPOST_VIEWS_BY_DATE = "GET_JOBPOST_VIEWS_BY_DATE";
export const GET_JOBPOST_VIEWS_BY_DATE_SUCCESS =
  "GET_JOBPOST_VIEWS_BY_DATE_SUCCESS";
export const CHOOSE_PAYMENT_METHOD = "CHOOSE_PAYMENT_METHOD";
export const SEND_INVOICE_TO_TALOUS = "SEND_INVOICE_TO_TALOUS";
export const REGISTER_PAYMENT = "REGISTER_PAYMENT";
export const PROCESS_ONLINE_PAYMENT = "PROCESS_ONLINE_PAYMENT";
export const DISPLAY_PAYMENT_STATUS_MESSAGE = "DISPLAY_PAYMENT_STATUS_MESSAGE";
export const ADD_EXTRA_SERVICE = "ADD_EXTRA_SERVICE";
export const CHANGE_ROUTE = "CHANGE_ROUTE";
export const ADMIN_GET_USER_PROFILE = "ADMIN_GET_USER_PROFILE";
export const AUTO_EMAIL_TO_APPLICANT = "AUTO_EMAIL_TO_APPLICANT";
export const POPULATE_EMAIL_MESSAGE = "POPULATE_EMAIL_MESSAGE";

// APPLICATIONS DETAILS
export const GET_APPLICATION_DETAILS_BY_ID = "GET_APPLICATION_DETAILS_BY_ID";
export const GET_APPLICATION_DETAILS_BY_ID_SUCCESS =
  "GET_APPLICATION_DETAILS_BY_ID_SUCCESS";
export const UPDATE_APPLICANT_STATUS = "UPDATE_APPLICANT_STATUS";
export const UPDATE_JOB_APPLICATION_DETAILS = "UPDATE_JOB_APPLICATION_DETAILS";
export const EDIT_INTERVIEW_DETAILS = "EDIT_INTERVIEW_DETAILS";

// DELETE APPLICATIONS
export const WARN_TO_DELETE_APPLICATION = "WARN_TO_DELETE_APPLICATION";
export const DELETE_APPLICATION = "DELETE_APPLICATION";

// JOB POSTS LISTS
export const GET_ALL_ADS_BY_STATUS = "GET_ALL_ADS_BY_STATUS";
export const GET_ALL_ADS_BY_STATUS_SUCCESS = "GET_ALL_ADS_BY_STATUS_SUCCESS";

// LAYOUT COMPONENT
export const GET_AD_INFO_FROM_SIDE_MENU = "GET_AD_INFO_FROM_SIDE_MENU";
export const NAVIGATE_ADS_FROM_MAIN_MENU = "NAVIGATE_ADS_FROM_MAIN_MENU";

// Language Translation
export const LANGUAGE_CHANGE = "LANGUAGE_CHANGE";

// COMPANY PROFILE
export const ADD_COMPANY_PROFILE = "ADD_COMPANY_PROFILE";
export const GET_COMPANY_PROFILE = "GET_COMPANY_PROFILE";
export const GET_COMPANY_PROFILE_SUCCESS = "GET_COMPANY_PROFILE_SUCCESS";
export const GET_COMPANY_PROFILE_FAILED = "GET_COMPANY_PROFILE_FAILED";
export const ADD_NEW_COMPANY_START = "ADD_NEW_COMPANY_START";
export const ADD_NEW_COMPANY_END = "ADD_NEW_COMPANY_END";

/* export const SHOW_SUCCESS_SNACKBAR = 'SHOW_SUCCESS_SNACKBAR'
export const SHOW_FAILED_SNACKBAR = 'SHOW_FAILED_SNACKBAR'
export const CLOSE_PROFILE_SNACKBAR = 'CLOSE_PROFILE_SNACKBAR' */

export const GET_USER_COMPANIES_LIST = "GET_USER_COMPANIES_LIST";
export const GET_USER_COMPANIES_LIST_SUCCESS =
  "GET_USER_COMPANIES_LIST_SUCCESS";
export const SELECT_COMPANY = "SELECT_COMPANY";
export const SELECT_COMPANY_SUCCESS = "SELECT_COMPANY_SUCCESS";

// JOBSEEKERS
export const ADD_APPLICANT_PROFILE = "ADD_APPLICANT_PROFILE";
export const GET_APPLICANT_PROFILE = "GET_APPLICANT_PROFILE";
export const GET_APPLICANT_PROFILE_SUCCESS = "GET_APPLICANT_PROFILE_SUCCESS";
export const GET_FAVORITE_JOBS = "GET_FAVORITE_JOBS";
export const GET_FAVORITE_JOBS_SUCCESS = "GET_FAVORITE_JOBS_SUCCESS";
export const GET_APPLIED_JOBS = "GET_APPLIED_JOBS";
export const GET_APPLIED_JOBS_SUCCESS = "GET_APPLIED_JOBS_SUCCESS";
export const TOGGLE_FAVORITE_JOBS = "TOGGLE_FAVORITE_JOBS";
export const DELETE_FAVORITE_JOBS = "DELETE_FAVORITE_JOBS";
export const GET_APPLICANT_DASHBOARD_INFO = "GET_APPLICANT_DASHBOARD_INFO";
export const GET_APPLICANT_DASHBOARD_INFO_SUCCESS =
  "GET_APPLICANT_DASHBOARD_INFO_SUCCESS";
export const TOGGLE_EMAIL_NOTIFICATION = "TOGGLE_EMAIL_NOTIFICATION";
export const UPDATE_EMAIL_NOTIFICATION = "UPDATE_EMAIL_NOTIFICATION";
// SEND APPLICATION
export const SEND_APPLICATION = "SEND_APPLICATION ";
export const SEND_APPLICATION_SUCCESS = "SEND_APPLICATION_SUCCESS ";
export const RESET_APPLICATION_SENT = "RESET_APPLICATION_SENT";
// SHOW APPLICATIONS PER PAGE OPTIONS
export const CHANGE_ROWS_PER_PAGE = "CHANGE_ROWS_PER_PAGE";

// POPULATE SIGNUP FORM
export const POPULATE_SIGNUP_FORM = "POPULATE_SIGNUP_FORM";

// ADMINS
export const ADMIN_SEARCH_COMPANY = "ADMIN_SEARCH_COMPANY";
export const ADMIN_SEARCH_COMPANY_SUCCESS = "ADMIN_SEARCH_COMPANY_SUCCESS";
export const ADMIN_SEARCH_APPLICANT = "ADMIN_SEARCH_APPLICANT";
export const ADMIN_SEARCH_APPLICANT_SUCCESS = "ADMIN_SEARCH_APPLICANT_SUCCESS";
export const ADMIN_SEARCH_INVOICE = "ADMIN_SEARCH_INVOICE";
export const ADMIN_SEARCH_INVOICE_SUCCESS = "ADMIN_SEARCH_INVOICE_SUCCESS";
export const ADMIN_SEARCH_ADS_MARKETING = "ADMIN_SEARCH_ADS_MARKETING";
export const ADMIN_SEARCH_ADS_MARKETING_SUCCESS =
  "ADMIN_SEARCH_ADS_MARKETING_SUCCESS";
export const ADMIN_UPDATE_MARKETING_STATUS = "ADMIN_UPDATE_MARKETING_STATUS";
export const ADMIN_EXPAND_AD_ROW = "ADMIN_EXPAND_AD_ROW";
export const ADMIN_CLOSE_AD_ROW = "ADMIN_CLOSE_AD_ROW";
export const GET_MARKETING_BUDGET_SUCCESS = "GET_MARKETING_BUDGET_SUCCESS";
export const EDIT_CONTACT_DETAILS = "EDIT_CONTACT_DETAILS";
export const CANCEL_EDIT_CONTACT_DETAILS = "CANCEL_EDIT_CONTACT_DETAILS";
export const ADMIN_UPDATE_USER_PROFILE = "ADMIN_UPDATE_USER_PROFILE";
export const ADMIN_UPDATE_USER_PROFILE_SUCCESS =
  "ADMIN_UPDATE_USER_PROFILE_SUCCESS";
export const ADMIN_UPDATE_USER_PROFILE_FAIL = "ADMIN_UPDATE_USER_PROFILE_FAIL";
export const ADMIN_SEARCH_ADDITIONAL_SERVICE =
  "ADMIN_SEARCH_ADDITIONAL_SERVICE";
export const ADMIN_SEARCH_ADDITIONAL_SERVICE_SUCCESS =
  "ADMIN_SEARCH_ADDITIONAL_SERVICE_SUCCESS";
export const UPDATE_PAYMENT_STATUS = "UPDATE_PAYMENT_STATUS";

// ASYNC ACTIONS SNACKBAR
export const SHOW_SUCCESS_SNACKBAR = "SHOW_SUCCESS_SNACKBAR";
export const SHOW_FAILED_SNACKBAR = "SHOW_FAILED_SNACKBAR";
export const SHOW_CUSTOM_ERROR_MESSAGE = "SHOW_CUSTOM_ERROR_MESSAGE";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const SHOW_DIALOG = "SHOW_DIALOG";
export const CLOSE_DIALOG = "CLOSE_DIALOG";

//search companies
export const SEARCH_COMPANY_DETAILS = "SEARCH_COMPANY_DETAILS";

//get company details
export const SEARCH_COMPANY_DETAILS_SUCCESS = "SEARCH_COMPANY_DETAILS_SUCCESS";

// fetch company addresses
export const LOAD_SELECTED_COMPANY = "LOAD_SELECTED_COMPANY";

// CLOSE DIALOGBOX
export const CLOSE_COMPANY_LISTS = "CLOSE_COMPANY_LISTS";

// Page size defaults for list of job posts

export const JOBPOST_COUNT_PER_PAGE = 20;
export const ADMIN_VIEW_COUNT_PER_PAGE = 20;

export const mol_page_url = "https://www.tootukassa.ee/et/toopakkumised";

export const HELP_SERVICE_FEE = 30;
export const SOS_SERVICE_FEE = 90;

// Development Server
export const API_SERVER = "https://vpt-api-dev.azurewebsites.net/api";
export const API_SERVER_EST = "https://localhost:7262/jobsEn";
export const ESTONIAN_USER_VALIDATE = "https://localhost:7262/CheckUser";
export const ESTONIAN_USER_REGISTER = "https://localhost:7262/api/User";
export const ESTONIAN_GET_APPLICANT_PROFILE =
  "https://localhost:7262/getAllApplicants";
export const API_SERVER_UPDATE_COMPANY_INFO =
  "https://localhost:7262/fillCompanyInfo";
export const API_SERVER_EST_GET_ID = "https://localhost:7262/JobOffer";
export const VPT_IDENTITY_SERVER =
  "https://vpt-identityserver-dev.azurewebsites.net/api";

// Production Server
// export const API_SERVER = 'https://vpt-api-prod.azurewebsites.net/api';
// export const VPT_IDENTITY_SERVER = 'https://vpt-identityserver-prod.azurewebsites.net/api';

// Local Server
// export const API_SERVER = 'https://www.tootukassa.ee/etootukassa/api/toopakkumised';
